---
- name: debian | installing pre-reqs
  apt:
    name:
      - openjdk-8-jre-headless
      - git
      - python-mysqldb
    state: present

- name: debian | installing gitweb (if enabled)
  apt:
    name: gitweb
    state: present
  when: gerrit_gitweb_integration is defined and gerrit_gitweb_integration
